<?php


/**
 * Implements hook_menu().
 */
function robin_menu() {
  $items = array();
  
  $items['admin/config/administration/robin'] = array(
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('robin_admin_form'),
    'title' => 'Robin admin',
    'description' => 'Change settings for the robin module',
  );
  
  return $items;
}

/**
 * Admin for robin module.
 */
function robin_admin_form($form, &$form_state) {
  
  $form['robin_num_items_blog'] = array(
    '#type' => 'select',
    '#title' => t('Number of items per block'),
    '#description' => t('Description'),
    '#options' => array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
    '#default_value' => variable_get('robin_num_items_blog', 5),
  );
  
  return system_settings_form($form);
}

/**
 * Implements hook_views_pre_build().
 */
function robin_views_pre_build(&$view) {
  if (($view->name == 'blog') && ($view->current_display == 'block')) {
    $view->items_per_page = variable_get('robin_num_items_blog', 5);
  }
}
